### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by necantis** [lse-me314/assignment05#1]
Exercise 5.1.a: which example should be used to create a binary variable, `mpg01`, that contains a 1 if `mpg` contains a value above its median, and a 0 if `mpg` contains a value below its median ? 
The lab section of chapter 4 uses contrasts(), but it can be applied to mpg because it is not categorical. 

Exercise 5.1.c: the criteria to split train and test data is not given. 
For example, in the lab section of chapter 4, all data before a specific date is considered as training data.

**Comment by chmue** [comment]
For 5.1a you can use any code which produces the desired variable. See exercise 1 in assignment 1 for a possible way (or ask your friendly neighbourhood search engine).

For 5.1c you can use any (sensible) split which creates two sets with roughly equal numbers of observations.
