### ISSUE TITLE
Best K for Exercise 5.1.g

### ISSUE THREAD

**Issue by necantis** [lse-me314/assignment05#2]
The current code sets the seed only once.
Hence the tests of K=10 and K=100 are done with a different seed.

If the seed is set at 1, the better error rate (13.7%) is achieved setting k=3 
`set.seed(1)
knn.pred <-  knn(train.X, test.X, train.mpg01, k = 3)
mean(knn.pred != mpg01.test)`

**Comment by chmue** [comment]
> Hence the tests of K=10 and K=100 are done with a different seed.

This is not really an issue. The point of setting the seed is to make the computation replicable across reruns of the code and for this it is enough to set the seed once at the beginning of the script (or the R chunk where you use random numbers just make sure that you run `set.seed()` every time you run the associated code chunk).

KNN uses random numbers in the initialization step of the algorithm (and in the binary outcome case to break ties if `k` is even and the two classes are equi-distributed among the k-neighbours). The algorithm itself has no random parts and it converges when there are no more changes between iterations. The stable distribution *should* be reached independent of the random initialization and it will in most of the cases.

However, there are cases where the seed actually matters. If this is the case, you should interpret the results very cautiously.
